name: bsm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=2.2
  - pyarrow>=15
  - numpy>=1.26
  - scipy>=1.11
  - pyyaml>=6.0
  - tqdm>=4.66
  - matplotlib>=3.8
  - seaborn>=0.13
  - geopandas>=0.14
  - shapely>=2.0
  - cvxpy>=1.4
  - pip
